# Generated by Django 5.0.6 on 2024-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectera_main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=30)),
                ("titles", models.CharField(max_length=40)),
                ("descriptions", models.CharField(max_length=500)),
                ("images1", models.ImageField(default="", upload_to="clients/images")),
                (
                    "images2",
                    models.ImageField(default="", upload_to="project_main/images"),
                ),
                (
                    "project_zips",
                    models.FileField(null=True, upload_to="project_main_file"),
                ),
            ],
        ),
    ]
