# Generated by Django 5.0.6 on 2024-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectera_main", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="images1",
            field=models.ImageField(default="", upload_to="User/images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="images2",
            field=models.ImageField(default="", upload_to="project_main_user/images"),
        ),
    ]
