# Generated by Django 5.0.6 on 2024-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectera_main", "0003_projects_project_number_alter_user_images1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=10)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
